name: Command

# NB: **ALL** commands should be permissionless and only use an app token or relevant secrets
#   specific to their requirements!
permissions:
  contents: read

on:
  issue_comment:
    types:
    - created

env:
  CI_DEBUG: ${{ vars.CI_DEBUG }}


jobs:
  # For speed and _security_ only a single command (first matching) will be parsed/run from a comment
  command:
    name: Parse and run command
    runs-on: ubuntu-22.04
    if: >-
      ${{
         github.event.issue.pull_request
         && github.actor != 'repokitteh-read-only[bot]'
         && github.actor != 'dependabot[bot]'
      }}
    steps:
    # /retest
    - uses: envoyproxy/toolshed/gh-actions/appauth@a3b5575be022262749dc1d8d13cd6921f28340dc  # actions-v0.2.20
      id: appauth-retest
      name: Appauth (retest)
      with:
        key: ${{ secrets.ENVOY_CI_APP_KEY }}
        app_id: ${{ secrets.ENVOY_CI_APP_ID }}
    - uses: envoyproxy/toolshed/gh-actions/retest@a3b5575be022262749dc1d8d13cd6921f28340dc  # actions-v0.2.20
      name: Retest
      with:
        token: ${{ steps.appauth-retest.outputs.token }}
